<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE help [
<!ENTITY lt "#38;#60;">
<!ENTITY gt "&#62;">
<!ENTITY amp "&#38;#38;">
<!ELEMENT help (name , synopsis , description , arguments+ , outputs* , example* , bugs* , reporting* , see-also*)*>
<!ELEMENT name (#PCDATA)>
<!ELEMENT synopsis (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT arguments (positional* , required-flagged* , optional-flagged*)*>
<!ELEMENT positional (intro* , argument* , explanation*)*>
<!ELEMENT required-flagged (intro* , argument* , explanation*)*>
<!ELEMENT optional-flagged (intro* , argument* , explanation*)*>
<!ELEMENT intro (#PCDATA)>
<!ELEMENT argument (#PCDATA)>
<!ELEMENT explanation (#PCDATA)>
<!ELEMENT outputs (output* , explanation*)>
<!ELEMENT output (#PCDATA)>
<!ELEMENT example (#PCDATA)>
<!ELEMENT bugs (#PCDATA)>
<!ELEMENT reporting (#PCDATA)>
<!ELEMENT see-also (#PCDATA)>
]>

<help>
  <name>mris_apply_reg</name>
  <synopsis>mris_apply_reg</synopsis>
  <description> mris_apply_reg applys surface registration.
</description>
  <arguments>
    <required-flagged>
      <intro>None</intro>
      <argument>--src srcvalfile (or use --i)</argument>
      <explanation> Input file that supplies the source values to convert</explanation>
      <argument>--trg trgvalfile (or use --o)</argument>
      <explanation> Output file</explanation>
      <argument>--streg srcreg1 trgreg1</argument>
      <explanation> source-target registration pair</explanation>
      <argument>--lta source-surf ltafile outputsurf</argument>
      <explanation> apply an LTA registration to a surface</explanation>
      <argument>--lta-rot source-surf ltafile outputsurf</argument>
      <explanation> apply just the rotational components of an LTA registration to a surface</explanation>
      <argument>--center</argument>
      <explanation> force xyz of centroid to be 0</explanation>
    </required-flagged>
    <optional-flagged>
      <argument>--streg srcreg2 trgreg2</argument>
      <explanation> source-target registration pair</explanation>
      <argument>--curv</argument>
      <explanation> Save output in curv format</explanation>
      <argument>--map-vertex vertexno srcsurf trgsurf outfile</argument>
      <explanation> Map vertex from source to target (stand-alone)</explanation>
      <argument>--warp source-surf gcamfile outputsurf</argument>
      <explanation> stand-alone to apply a GCA morph registration to a surface (was --m3z/--gcam)</explanation>
      <argument>--vg-thresh thresh</argument>
      <explanation> Set thresh for comparing VolGeom (put BEFORE --warp/--m3z/--gmca)</explanation>
      <argument>--bci input srcreg trgreg output</argument>
      <explanation> stand-alone to map input to target via barycentric interpoloation </explanation>
      <argument>--bci-xyz inputsurf srcreg trgreg output</argument>
      <explanation> stand-alone to map input surface xyz to target via barycentric interpoloation </explanation>
      <argument>--reg-scanner-ras</argument>
      <explanation> Convert registration surfaces to scanner RAS </explanation>
      <argument>--xzy-scanner-ras</argument>
      <explanation> Convert input surface xyz to scanner RAS, apply xform, then convert back to TkReg RAS </explanation>
    </optional-flagged>
  </arguments>
  <example>
Map the lh thickness into the symmetric space
mris_apply_reg --src lh.thickness --trg xhemi.lh.thickness \
   --streg $SUBJECTS_DIR/$subject/surf/lh.fsaverage_sym.sphere.reg \
              $SUBJECTS_DIR/fsaverage_sym/surf/lh.sphere.reg
  </example>
  <example>

Map the rh thickness into the symmetric space
mris_apply_reg --src rh.thickness --trg xhemi.rh.thickness \
   --streg $SUBJECTS_DIR/$subject/xhemi/surf/lh.fsaverage_sym.sphere.reg \
              $SUBJECTS_DIR/fsaverage_sym/surf/lh.sphere.reg

Note that lh.fsaverage_sym.sphere.reg is used.  This is intentional; the left hemis in the xhemi folder are actually right hemis.

  </example>
  <example>
    Map a label from the left hemi to the right hemi
    mris_apply_reg --src-label lh.source.label \
     --streg lh.sphere.left_right rh.sphere.left_right \
     --trg rh.lh.source.label
  </example>

  <example>
    Map a surface from the anatomical space to fMRI space.
    First, you have to get an LTA registration file (eg, with bbregister)
    mris_apply_reg --lta lh.white fmri.reg.lta ./lh.white.fmri
  </example>

  <bugs>None</bugs>
  <reporting>Report bugs to &lt;freesurfer@nmr.mgh.harvard.edu&gt;</reporting>
  <see-also>mris_convert</see-also>
</help>

